name: my-app

configs:
  Debug: debug
  Release: release
  Adhoc: release
  Beta: release

configFiles:
  Debug: config/iOS/xcconfig/Debug.xcconfig
  Release: config/iOS/xcconfig/Release.xcconfig
  Adhoc: config/iOS/xcconfig/Adhoc.xcconfig
  Beta: config/iOS/xcconfig/Beta.xcconfig

############
# Options
############

options:
  createIntermediateGroups: true
  groupSortPosition: top
  generateEmptyDirectories: true
  indentWidth: 4
  tabWidth: 4
  bundleIdPrefix: "com.thanhthan"


############
# Settings
############

settings:
  PRODUCT_BUNDLE_IDENTIFIER: $(AS_BUNDLE_IDENTIFIER)

############
# Packages
############

packages:
  Alamofire:
    url: https://github.com/Alamofire/Alamofire.git
    exactVersion: 5.12.0
  Lottie:
    url: https://github.com/airbnb/lottie-spm.git
    exactVersion: 4.6.1
  SDWebImage:
    url: https://github.com/SDWebImage/SDWebImage.git
    exactVersion: 5.21.7
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    exactVersion: 1.26.2
  TCACoordinators:
    url: https://github.com/johnpatrickmorgan/TCACoordinators.git
    exactVersion: 0.16.0
  XCTestDynamicOverlay:
    url: https://github.com/pointfreeco/xctest-dynamic-overlay
    exactVersion: 1.13.1

############
# Targets
############

targets:
  my-app:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
    - Sources
    dependencies:
      - package: Alamofire
      - package: Lottie
      - package: SDWebImage
      - package: ComposableArchitecture
      - package: TCACoordinators
    attributes:
      SystemCapabilities:
        com.apple.Push:
          enabled: 1
    configFiles:
      Debug: config/iOS/xcconfig/Debug.xcconfig
      Release: config/iOS/xcconfig/Release.xcconfig
      Adhoc: config/iOS/xcconfig/Adhoc.xcconfig
      Beta: config/iOS/xcconfig/Beta.xcconfig
    settings:
      ASSETCATALOG_COMPILER_APPICON_NAME: $(AS_APP_ICON)
      SWIFT_VERSION: "6.0"
      CODE_SIGN_STYLE: "Manual"
      TARGETED_DEVICE_FAMILY: 1
    scheme:
      testTargets:
        - my-appTests
      gatherCoverageData: true
      environmentVariables:
        ENABLE_SIGNPOST: YES

  my-appTests:
    type: bundle.unit-test
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - Tests
    dependencies:
      - target: my-app
      - package: XCTestDynamicOverlay
        product: IssueReportingTestSupport
    settings:
      SWIFT_VERSION: "6.0"
